#!/bin/bash


# move this script next to a folder named ${folder} containing all $id/results/$id folders generated by main script, 
# for example go to 111111/results/111111, take the inner 111111 forlder and copy it to your new results folder (a default folder named $folder has been already created)

all_files=""

folder="subjects"

while [[ "$1" != "" ]]; do
	case $1 in
		-f | --folder )
			shift
			folder=$1
			;;
		-h | --help )
			printf "Usage: ./script [-f <folder_name>]\n"
			exit
			;;
		* )
			echo "Unknown option, abort"
			exit
			;;
	esac
	shift
done

if ! [[ -d "$folder" ]]; then
	printf "\nfolder: $folder doesn't exist\nUsage: ./script [-f <folder_name>]\n"
	exit
fi

for entry in "${folder}"/*; do
	# entry now becomes just subject number
	entry=${entry#"${folder}/"}

	# ignore other files
	if ! [[ "$entry" == ?????? && "$entry" =~ ^[0-9]+$ ]]; then
		printf "\nfolder: $folder is empty or contains wrong folders\nUsage: ./script [-f <folder_name>]\n"
		exit
	fi

	if [[ "$entry" == ?????? && "$entry" =~ ^[0-9]+$ ]]; then
		touch ${folder}/${entry}/networks.txt

		# extract last column from full results and store it in networks.txt
		cat ${folder}/${entry}/Schaefer_full_results_${entry}.txt | awk '{print $NF}' > ${folder}/${entry}/networks.txt

		# create
		all_files="${all_files} ${folder}/${entry}/networks.txt"

		echo "$entry added"
	fi

done

paste -d '\t' $all_files > ${folder}_networks.txt

echo running choose_reorganization.m ...
matlab -nodisplay -nosplash -nodesktop -r "choose_reorganization('${folder}_networks.txt', 'networks.txt', 'reorganization.txt');exit" | tail -n +11
echo done

mv networks.txt ${folder}_final_networks.txt
mv reorganization.txt ${folder}_reorganization.txt
rm ${folder}_networks.txt
