#!/bin/bash


# create a folder containing all $id/results/$id folders generated by main script, move it in the current folder and run the script with -f <folder_name>
# for example go to 111111/results/111111, take the inner 111111 folder and copy it to your new results folder

all_files=""

folder="subjects"

while [[ "$1" != "" ]]; do
	case $1 in
		-f | --folder )
			shift
			folder=$1
			;;
		-h | --help )
			printf "Usage: ./script [-f <folder_name>]\n"
			exit
			;;
		* )
			echo "Unknown option, abort"
			exit
			;;
	esac
	shift
done

if ! [[ -d "$folder" ]]; then
	printf "\nfolder: $folder doesn't exist\nUsage: ./script [-f <folder_name>]\n"
	exit
fi

for entry in "${folder}"/*; do
	# entry now becomes just subject number
	entry=${entry#"${folder}/"}

	# ignore other files
	if ! [[ "$entry" == ?????? && "$entry" =~ ^[0-9]+$ ]]; then
		printf "\nfolder: $folder is empty or contains wrong folders\nUsage: ./script [-f <folder_name>]\n"
		exit
	fi

	if [[ "$entry" == ?????? && "$entry" =~ ^[0-9]+$ ]]; then
		touch ${folder}/${entry}/networks.txt

		# extract last column from full results and store it in networks.txt
		cat ${folder}/${entry}/Schaefer_full_results_${entry}.txt | awk '{print $NF}' > ${folder}/${entry}/networks.txt

		# create string containing all files
		all_files="${all_files} ${folder}/${entry}/networks.txt"

		echo "$entry added"
	fi

done
# merge all networks in a single file
paste -d '\t' $all_files > ${folder}_networks.txt
# remove networks.txt file from each folder
rm $all_files

# this script chooses the most frequent network for each region, see the script for more explanation
echo running choose_reorganization.m ...
matlab -nodisplay -nosplash -nodesktop -r "choose_reorganization('${folder}_networks.txt', 'networks.txt', 'reorganization.txt');exit" | tail -n +11
echo done

mv networks.txt ${folder}_final_networks.txt
mv reorganization.txt ${folder}_reorganization.txt

# if you need to keep the file with all networks assigned for each subject, just comment the next line
rm ${folder}_networks.txt
